---
name: ci

on:
  push:
    branches:
      - "*"

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.7"
      - name: "Test"
        run: make test
